// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Patient struct {
	ID          string `json:"id"`
	Firstname   string `json:"firstname"`
	Lastname    string `json:"lastname"`
	Dateofbirth string `json:"dateofbirth"`
	Gender      string `json:"gender"`
}

type Query struct {
}
